src/CouchbaseGlimpseWeb/Controllers/BreweriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CouchbaseBeersWeb.Models;

namespace CouchbaseBeersWeb.Controllers
{
	public class BreweriesController : Controller
	{
		public BreweryRepository BreweryRepository { get; set; }

		public BreweriesController()
		{
			BreweryRepository = new BreweryRepository();
		}

		//
		// GET: /Breweries/

		public ActionResult Index(string startKey, int pageSize = 25)
		{
			var breweries = BreweryRepository.GetAllByName(startKey: startKey, limit: pageSize + 1);
			ViewBag.StartKey = breweries.ElementAt(0).Name;
			ViewBag.NextStartKey = breweries.ElementAt(breweries.Count() - 1).Name;
			return View(breweries.Take(pageSize));
		}

		//
		// GET: /Breweries/Details/5

		public ActionResult Details(string id)
		{
			var brewery = BreweryRepository.GetWithBeers(id);
			return View(brewery);
		}

		//
		// GET: /Breweries/Create

		public ActionResult Create()
		{
			return View();
		}

		//
		// POST: /Breweries/Create

		[HttpPost]
		public ActionResult Create(Brewery brewery)
		{
			BreweryRepository.Create(brewery);
			return RedirectToAction("Index");
		}

		//
		// GET: /Breweries/Edit/5

		public ActionResult Edit(string id)
		{
			var brewery = BreweryRepository.Get(id);
			return View(brewery);
		}

		//
		// POST: /Breweries/Edit/5

		[HttpPost]
		public ActionResult Edit(string id, Brewery brewery)
		{
			BreweryRepository.Update(brewery);
			return RedirectToAction("Index");
		}

		//
		// GET: /Breweries/Delete/5

		public ActionResult Delete(string id)
		{
			var brewery = BreweryRepository.Get(id);
			return View(brewery);
		}

		//
		// POST: /Breweries/Delete/5

		[HttpPost]
		public ActionResult Delete(string id, Brewery brewery)
		{
			BreweryRepository.Delete(id);
			return RedirectToAction("Index");
		}
	}
}

src/CouchbaseGlimpseWeb/Controllers/CountriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CouchbaseBeersWeb.Models;

namespace CouchbaseBeersWeb.Controllers
{
	public class CountriesController : Controller
	{
		public BreweryRepository BreweryRepository { get; set; }

		public CountriesController()
		{
			BreweryRepository = new BreweryRepository();
		}

		public ActionResult Index()
		{
			var grouped = BreweryRepository.GetGroupedByLocation(BreweryGroupLevels.Country);
			return View(grouped);
		}

		public ActionResult Provinces(string country)
		{
			var grouped = BreweryRepository.GetGroupedByLocation(
						BreweryGroupLevels.Province, new string[] { country });
			return View(grouped);
		}

		public ActionResult Cities(string country, string province)
		{
			var grouped = BreweryRepository.GetGroupedByLocation(
						BreweryGroupLevels.City, new string[] { country, province });
			return View(grouped);
		}

		public ActionResult Codes(string country, string province, string city)
		{
			var grouped = BreweryRepository.GetGroupedByLocation(
						BreweryGroupLevels.PostalCode, new string[] { country, province, city });
			return View(grouped);
		}

		public ActionResult Details(string country, string province, string city, string code)
		{
			var breweries = BreweryRepository.GetByLocation(country, province, city, code);
			return View(breweries);
		}
	}
}

src/CouchbaseGlimpseWeb/Views/Countries/Cities.cshtml
@model dynamic

<h2>Breweries counts by city in @Request["province"], @Request["country"]</h2>

<ul>
@foreach (KeyValuePair<string, int> item in Model)
{
    <li>
        @Html.ActionLink(item.Key, "Codes",
            new { country = Request["country"], 
                  province = Request["province"], 
                  city = item.Key})
        (@item.Value)
    </li>
}
</ul>

src/CouchbaseGlimpseWeb/Views/Countries/Codes.cshtml
@model dynamic

<h2>Brewery counts by postal code in @Request["city"], @Request["province"], @Request["country"]</h2>

<ul>
@foreach (KeyValuePair<string, int> item in Model)
{
    <li>
       @Html.ActionLink(item.Key, "Details",
            new { country = Request["country"], 
                  province = Request["province"], 
                  city = Request["city"],
                  code = item.Key})
        (@item.Value)        
    </li>
}
</ul>

@Html.ActionLink("Back to Country List", "Index")

src/CouchbaseGlimpseWeb/Views/Countries/Details.cshtml
@model IEnumerable<CouchbaseBeersWeb.Models.Brewery>

@{
    ViewBag.Title = "Details";
}

<h2>Breweries in @Request["code"], @Request["city"], @Request["province"], @Request["country"]</h2>

<ul>
@foreach (var item in Model)
{
    <li>
        @Html.ActionLink(item.Name, "Details", "Breweries", new { id = item.Id }, new { })
    </li>
}
</ul>

@Html.ActionLink("Back to Country List", "Index")

src/CouchbaseGlimpseWeb/Views/Countries/Index.cshtml
@model dynamic

<h2>Brewery counts by country</h2>

<ul>
@foreach (KeyValuePair<string, int> item in Model)
{
    <li>
        @Html.ActionLink(item.Key, "Provinces",
            new { country = item.Key})
        (@item.Value)
    </li>
}
</ul>

src/CouchbaseGlimpseWeb/Views/Countries/Provinces.cshtml
@model dynamic


<h2>Brewery counts by province in @Request["country"]</h2>


<ul>
@foreach (KeyValuePair<string, int> item in Model)
{
    <li>
        @Html.ActionLink(item.Key, "Cities",
            new { country = Request["country"], province = item.Key})
        (@item.Value)
    </li>
}
</ul>